### ISSUE TITLE
[Feature] Add License

### ISSUE THREAD

**Issue by Dynnammo** [Cedar-Cat-Studios/dbt_query_game#15]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Adding a License file to your project, since without license your project is considered proprietary (and may still be, no troubles, but it should be clearer to folks making PRs or wanting to improve it).

You can check https://choosealicense.com/ to help you choose wisely

**Comment by JoeMark17** [comment]
This is a great thing to callout! Thanks for opening this feature request @Dynnammo. I will look into adding a license in the future!

**Comment by JoeMark17** [comment]
This is a great thing to callout! Thanks for opening this feature request @Dynnammo. I will look into adding a license in the future!

**Comment by JoeMark17** [comment]
Thanks again for opening this issue @Dynnammo! I have been able to add the MIT license to the project. Closing this issue 😸
