### ISSUE TITLE
[Bug] End Screen Adjustments

### ISSUE THREAD

**Issue by JessicaKMarkiewicz** [Cedar-Cat-Studios/dbt_query_game#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When prompted with the end screen, it should say "QUERY;" instead of "daily SQL puzzle" so language remains consistent. Additionally, the "View Answer" button does not work as intended as the user has to click it three times for the answer to properly populate.

### Expected behavior

When clicking the "View Answer" button, the answer should populate after the first click.

### Game version

0.2.2

**Comment by JoeMark17** [comment]
Hi @JessicaAKelley thanks so much for opening this issue!

The adjustment of the end screen wording is a great one and something I was able to adjust on my end. I also was able to fix the "View Answer" button as well so it properly populates on the first click.

I haven't released a new cut version of the game, but the fixes from this issue will be resolved in `v0.2.3`. I will close the issue out once the release is live.
